### ISSUE TITLE
Individual coloring of hexagons

### ISSUE THREAD

**Issue by nickclason** [alexkaz2/hexalattice#1]
Is it possible to control the color of individual hexagons or can it only be done at a grid level? If this can be done, how can it be achieved?

**Comment by alexkaz2** [comment]
Hi,
Currently individual coloring is not supported, but can be added rather easily:

1. Allow [plot_single_lattice() ](https://github.com/alexkaz2/hexalattice/blob/5d292cca1738727c2a7e762dd609870b50a5adb9/hexalattice/hexalattice.py#L121)to accept lists of colors, instead of single color for edge and face.
2. Add the color argument to the hexagon creation [inside the for() loop](https://github.com/alexkaz2/hexalattice/blob/5d292cca1738727c2a7e762dd609870b50a5adb9/hexalattice/hexalattice.py#L137)
3. Remove the uniform coloring from the [PatchCollection drawing](https://github.com/alexkaz2/hexalattice/blob/5d292cca1738727c2a7e762dd609870b50a5adb9/hexalattice/hexalattice.py#L141)

It so might happen that the PatchCollection doesn't support individual coloring of its patches. In this case the patches are to be added directly to the canvas during the for() loop, and not use the PatchCollection at all.

I hope it will work out for you,
Alex

**Comment by nickclason** [comment]
Thanks

**Comment by on46zohu** [comment]
> It so might happen that the PatchCollection doesn't support individual coloring of its patches. In this case the patches are to be added directly to the canvas during the for() loop, and not use the PatchCollection at all.

Hello, I tried to apply this, but I apparently failed to understand. Could you please help with that?

**Comment by alexkaz2** [comment]
Individual colors are supported as of today
